name: Docker Image CD

on:
  push:
    branches: [ "master" ] 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checl out the code base
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t shekharalpula/continuous_php_image
